=== Jegeva/ads2svd/in/Schemas/core_register_definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.arm.com/core_reg" 
        xmlns="http://www.arm.com/core_reg" 
        elementFormDefault="qualified"
        xmlns:xi="http://www.w3.org/2001/XInclude"
        xmlns:tcf="http://com.arm.targetconfigurationeditor">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2009/01/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/XInclude.xsd"/>
    <xs:import namespace="http://com.arm.targetconfigurationeditor" schemaLocation="board-01.xsd"/>

    <!-- Definition of root element register List -->
    <xs:element name="register_list" type="register_list_type"/>
  
  
    <!--  Define "container" element (used in include files) -->
    <xs:element name="container">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="register_list" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>  
        </xs:complexType>
    </xs:element>
  
    <!-- Define Register Group Element -->
    <xs:element name="register_group">
        <xs:complexType>
        <xs:sequence>
            <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <!-- Define attributes for register group element -->
        <xs:attribute name="name" type="c_symbol_type" use="required"></xs:attribute>
        <xs:attribute name="filter" type="xs:string" />
        <xs:attribute name="display_by_default" type="booleanEnum"/>
        </xs:complexType>
    </xs:element>

    <!-- Define peripheral Element -->
    <xs:element name="peripheral">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="register" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <!-- Define attributes for peripheral element -->
            <xs:attribute name="name" type="c_symbol_type" use="required"></xs:attribute>
            <xs:attribute name="offset" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- Define gui_name element -->
    <xs:element name="gui_name">
        <xs:complexType mixed="true">
          <xs:attribute name="language" type="xs:language" use="required"/> 
        </xs:complexType>
    </xs:element>
  
    <!-- Define Description Element -->
    <xs:element name="description">
        <xs:complexType mixed="true">
        <xs:attribute name="language" type="xs:language" use="required"/> 
        </xs:complexType>
    </xs:element>
    
    <!--  Define Disable Condition Element -->
    <xs:element name="disable_condition" type="xs:string"/>
  
    <!-- Define Register Element -->
    <xs:element name="register">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="alias_name" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="device_name" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
                <xs:choice>
                  <xs:choice minOccurs="0" maxOccurs="unbounded">
                      <xs:element ref="bitField" minOccurs="0" maxOccurs="unbounded"/>
                      <xs:element ref="conditional" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:element ref="array" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
                <xs:element name="device_register" type="device_register_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="size" type="widthEnum" use="required" />
            <xs:attribute name="offset" type="xs:string" />
            <xs:attribute name="access" type="accessEnum" use="required"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="optional" default="Hex"/>
            <xs:attribute name="display_by_default" type="booleanEnum"/>
            <xs:attribute name="doclink" type="xs:string" />
            <xs:attribute name="hidden" type="booleanEnum"/>
        </xs:complexType>
    </xs:element>

    <!-- Define conditional inclusion of bitfields -->
    <xs:element name="conditional">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bitField" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="expr" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <!-- Define alias_name Element -->
    <xs:element name="alias_name" type="xs:string"/>
    
    <!-- Define bitField Element -->
    <xs:element name="bitField">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="definition" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="conditional" type="booleanEnum" use="optional"/>
            <xs:attribute name="enumerationId" use="optional"/>
            <xs:attribute name="high_bit" type="bitFieldSize" use="optional"/>
            <xs:attribute name="low_bit" type="bitFieldSize" use="optional"/>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="access" type="accessEnum" use="optional" default="RW"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="optional" default="Hex"/>
        </xs:complexType>
    </xs:element>

    <!-- Define array types -->
    <xs:element name="array">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="element_bits"  type="xs:decimal" use="required"/>
            <xs:attribute name="element_stride"  type="xs:decimal" use="optional"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="required"/>
            <xs:attribute name="index_from_lsb" type="booleanEnum" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="definition" type="bitFieldPattern" />
  
    <!-- User defined types -->
    
    <!-- Definition boolean enumeration-->
    <xs:simpleType name="booleanEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="false"/>
            <xs:enumeration value="true"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Definition width enumeration-->
    <xs:simpleType name="widthEnum">
          <xs:restriction base="xs:string">
            <xs:enumeration value="256"/>
            <xs:enumeration value="128"/>
            <xs:enumeration value="64"/>
            <xs:enumeration value="32"/>
            <xs:enumeration value="16"/>
            <xs:enumeration value="8"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="1"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Definition of Access enumeration -->
    <xs:simpleType name="accessEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RW"/>
            <xs:enumeration value="RO"/>
            <xs:enumeration value="WO"/>
            <xs:enumeration value="RMW"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Define Pattern for Bit field definition element -->
    <xs:simpleType name="bitFieldPattern">
        <xs:restriction base="xs:string">
        <xs:pattern value="((\[[0-9]+\])|(\[[0-9]+:[0-9]+\]))+"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Define range for bit fields -->
    <xs:simpleType name="bitFieldSize">
        <xs:restriction base="xs:decimal">
            <xs:maxInclusive value="31"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- <device_register name="D0" high_bit="31" low_bit="0" shift="0"/> -->
    <xs:complexType name="device_register_type">
        <xs:attribute name="name" type="tcf:NameType"/>
        <xs:attribute name="high_bit" type="bitFieldSize_128"/>
        <xs:attribute name="low_bit" type="bitFieldSize_128"/>
        <xs:attribute name="shift" type="xs:decimal"/>
    </xs:complexType>
    
    <xs:simpleType name="bitFieldSize_128">
        <xs:restriction base="xs:decimal">
            <xs:maxInclusive value="127"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="c_symbol_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_$][a-zA-Z_$0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="device_name">
        <xs:complexType mixed="true">
          <xs:attribute name="type" type="xs:string"/> 
        </xs:complexType>
    </xs:element>

    <!-- Format of bit field inclusion file -->
    <xs:element name="bitFields">
        <xs:complexType>
            <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="bitField" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="array" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="xml:specialAttrs"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="register_list_type">
        <xs:sequence>
            <xs:element name="access_world" type="tcf:addrTypeEnum" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="xi:include"/>
                <xs:element ref="register_group"/>
                <xs:element ref="peripheral" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:element ref="tcf:enumeration" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="filter" type="xs:string" />
        <xs:attribute name="display_by_default" type="booleanEnum"/>
        <xs:attribute name="override" type="booleanEnum"/>      
        <xs:attributeGroup ref="xml:specialAttrs"/>
    </xs:complexType>

    <!-- Definition of Access enumeration -->
    <xs:simpleType name="numericalDisplayFormat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hex"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="Int"/>
            <xs:enumeration value="UnsignedInt"/>
            <xs:enumeration value="Binary"/>
            <xs:enumeration value="Boolean"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Jegeva/ads2svd/in/Cores/Registers/CP15/Cortex-A5_VA2PA.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<register_list name="CP15"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://www.arm.com/core_reg"
               xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd"
               xmlns:tcf="http://com.arm.targetconfigurationeditor">

<register_group name="VAtoPA">
        <gui_name language="en">VA to PA Translation</gui_name>
        <description language="en">VA to PA Translation Registers</description>
        <register access="RW" name="PAR" size="4">
        <gui_name language="en">PAR</gui_name>
            <alias_name>CP15_PAR</alias_name>
            <device_name type="rvi">CP15_PAR</device_name>
            <device_name type="cadi">PAR</device_name>
        <description language="en">Physical Address Register</description>
        <bitField conditional="false" name="PA">
            <gui_name language="en">PA</gui_name>
            <description language="en">Contains the physical address after a successful translation</description>
            <definition>[31:12]</definition>
        </bitField>
        <bitField conditional="false" name="NS" enumerationId="GENERIC_CLEAR_SET">
            <gui_name language="en">NS</gui_name>
            <description language="en">Indicates the state of the NS attribute bit in the translation table</description>
            <definition>[9]</definition>
        </bitField>
        <bitField conditional="false" name="SH" enumerationId="PAR_NS">
            <gui_name language="en">SH</gui_name>
            <description language="en">Indicates shareable memory: 0 = nonshared 1 = shared</description>
            <definition>[7]</definition>
        </bitField>
        <bitField conditional="false" name="INNER" enumerationId="PAR_INNER">
            <gui_name language="en">INNER</gui_name>
            <description language="en">Indicates the inner attributes from the translation table</description>
            <definition>[6:4]</definition>
        </bitField>
        <bitField conditional="false" name="OUTER" enumerationId="PAR_OUTER">
            <gui_name language="en">OUTER</gui_name>
            <description language="en">Indicates the outer attributes from the translation table</description>
            <definition>[3:2]</definition>
        </bitField>
        <bitField conditional="false" name="Supersection" enumerationId="PAR_SS">
            <gui_name language="en">SS</gui_name>
            <description language="en">Indicates if the result is a supersection</description>
            <definition>[1]</definition>
        </bitField>
        <bitField conditional="false" name="DFSR" enumerationId="E_I_D_FAULT_STATUS">
            <gui_name language="en">DFSR</gui_name>
            <description language="en">Holds the FSR bits for the aborted address</description>
            <definition>[6:1]</definition>
        </bitField>
        <bitField conditional="false" name="F" enumerationId="PAR_F">
            <gui_name language="en">F</gui_name>
            <description language="en">Indicates that the translation succeeded</description>
            <definition>[0]</definition>
        </bitField>
    </register>
    <register access="WO" name="V2PCWPR" size="4">
        <gui_name language="en">V2PCWPR</gui_name>
        <alias_name>CP15_V2PCWPR</alias_name>
        <device_name type="rvi">CP15_V2PCWPR</device_name>
        <device_name type="cadi">V2PCWPR</device_name>
        <description language="en">VA-to-PA translation in the Current World with privileged read permission</description>
    </register>
    <register access="WO" name="V2PCWPW" size="4">
        <gui_name language="en">V2PCWPW</gui_name>
        <alias_name>CP15_V2PCWPW</alias_name>
        <device_name type="rvi">CP15_V2PCWPW</device_name>
        <device_name type="cadi">V2PCWPW</device_name>
        <description language="en">VA-to-PA translation in the Current World with privileged write permission</description>
    </register>
    <register access="WO" name="V2PCWUR" size="4">
        <gui_name language="en">V2PCWUR</gui_name>
        <alias_name>CP15_V2PCWUR</alias_name>
        <device_name type="rvi">CP15_V2PCWUR</device_name>
        <device_name type="cadi">V2PCWUR</device_name>
        <description language="en">VA-to-PA translation in the Current World with User read permission</description>
    </register>
    <register access="WO" name="V2PCWUW" size="4">
        <gui_name language="en">V2PCWUW</gui_name>
        <alias_name>CP15_V2PCWUW</alias_name>
        <device_name type="rvi">CP15_V2PCWUW</device_name>
        <device_name type="cadi">V2PCWUW</device_name>
        <description language="en">VA-to-PA translation in the Current World with User write permission</description>
    </register>
    <register access="WO" name="V2POWPR" size="4">
        <gui_name language="en">V2POWPR</gui_name>
        <alias_name>CP15_V2POWPR</alias_name>
        <device_name type="rvi">CP15_V2POWPR</device_name>
        <device_name type="cadi">V2POWPR</device_name>
        <description language="en">VA-to-PA translation in the Other World with privileged read permission</description>
    </register>
    <register access="WO" name="V2POWPW" size="4">
        <gui_name language="en">V2POWPW</gui_name>
        <alias_name>CP15_V2POWPW</alias_name>
        <device_name type="rvi">CP15_V2POWPW</device_name>
        <device_name type="cadi">V2POWPW</device_name>
        <description language="en">VA-to-PA translation in the Other World with privileged write permission</description>
    </register>
    <register access="WO" name="V2POWUR" size="4">
        <gui_name language="en">V2POWUR</gui_name>
        <alias_name>CP15_V2POWUR</alias_name>
        <device_name type="rvi">CP15_V2POWUR</device_name>
        <device_name type="cadi">V2POWUR</device_name>
        <description language="en">VA-to-PA translation in the Other World with User read permission</description>
    </register>
    <register access="WO" name="V2POWUW" size="4">
        <gui_name language="en">V2POWUW</gui_name>
        <alias_name>CP15_V2POWUW</alias_name>
        <device_name type="rvi">CP15_V2POWUW</device_name>
        <device_name type="cadi">V2POWUW</device_name>
        <description language="en">VA-to-PA translation in the Other World with User write permission</description>
    </register>
</register_group>

</register_list>

=== Jegeva/ads2svd/in/Cores/Registers/CP15/Cortex-A5_TLB.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<register_list name="CP15"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://www.arm.com/core_reg"
               xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd"
               xmlns:tcf="http://com.arm.targetconfigurationeditor">

<register_group name="TLB">
        <gui_name language="en">TLB</gui_name>
        <description language="en">TLB Operations</description>
    <register access="WO" name="TLBIALLIS" size="4">
        <gui_name language="en">TLBIALLIS</gui_name>
        <alias_name>CP15_TLBIALLIS</alias_name>
        <device_name type="rvi">CP15_TLBIALLIS</device_name>
        <device_name type="cadi">TLBIALLIS</device_name>
        <description language="en">Invalidate entire Unified TLB Inner Shareable</description>
    </register>
    <register access="WO" name="TLBIMVAIS" size="4">
        <gui_name language="en">TLBIMVAIS</gui_name>
        <alias_name>CP15_TLBIMVAIS</alias_name>
        <device_name type="rvi">CP15_TLBIMVAIS</device_name>
        <device_name type="cadi">TLBIMVAIS</device_name>
        <description language="en">Invalidate Unified TLB entry by MVA Inner Shareable</description>
    </register>
    <register access="WO" name="TLBIASIDIS" size="4">
        <gui_name language="en">TLBIASIDIS</gui_name>
        <alias_name>CP15_TLBIASIDIS</alias_name>
        <device_name type="rvi">CP15_TLBIASIDIS</device_name>
        <device_name type="cadi">TLBIASIDIS</device_name>
        <description language="en">Invalidate Unified TLB entry by ASID match Inner Shareable</description>
    </register>
    <register access="WO" name="TLBIMVAAIS" size="4">
        <gui_name language="en">TLBIMVAAIS</gui_name>
        <alias_name>CP15_TLBIMVAAIS</alias_name>
        <device_name type="rvi">CP15_TLBIMVAAIS</device_name>
        <device_name type="cadi">TLBIMVAAIS</device_name>
        <description language="en">Invalidate Unified TLB entry by MVA all ASID Inner Shareable</description>
    </register>
    <register access="WO" name="TLBIALL" size="4">
        <gui_name language="en">TLBIALL</gui_name>
        <alias_name>CP15_TLBIALL</alias_name>
        <device_name type="rvi">CP15_TLBIALL</device_name>
        <device_name type="cadi">TLBIALL</device_name>
        <description language="en">Invalidate entire Unified TLB</description>
    </register>
    <register access="WO" name="TLBIMVA" size="4">
        <gui_name language="en">TLBIMVA</gui_name>
        <alias_name>CP15_TLBIMVA</alias_name>
        <device_name type="rvi">CP15_TLBIMVA</device_name>
        <device_name type="cadi">TLBIMVA</device_name>
        <description language="en">Invalidate Unified TLB by MVA</description>
    </register>
    <register access="WO" name="TLBIASID" size="4">
        <gui_name language="en">TLBIASID</gui_name>
        <alias_name>CP15_TLBIASID</alias_name>
        <device_name type="rvi">CP15_TLBIASID</device_name>
        <device_name type="cadi">TLBIASID</device_name>
        <description language="en">Invalidate TLB entries by ASID Match</description>
    </register>
    <register access="WO" name="TLBIMVAA" size="4">
        <gui_name language="en">TLBIMVAA</gui_name>
        <alias_name>CP15_TLBIMVAA</alias_name>
        <device_name type="rvi">CP15_TLBIMVAA</device_name>
        <device_name type="cadi">TLBIMVAA</device_name>
        <description language="en">Invalidate TLB entries by MVA All ASID</description>
    </register>
</register_group>

</register_list>
