=== Jegeva/ads2svd/in/Schemas/core_register_definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.arm.com/core_reg" 
        xmlns="http://www.arm.com/core_reg" 
        elementFormDefault="qualified"
        xmlns:xi="http://www.w3.org/2001/XInclude"
        xmlns:tcf="http://com.arm.targetconfigurationeditor">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2009/01/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/XInclude.xsd"/>
    <xs:import namespace="http://com.arm.targetconfigurationeditor" schemaLocation="board-01.xsd"/>

    <!-- Definition of root element register List -->
    <xs:element name="register_list" type="register_list_type"/>
  
  
    <!--  Define "container" element (used in include files) -->
    <xs:element name="container">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="register_list" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>  
        </xs:complexType>
    </xs:element>
  
    <!-- Define Register Group Element -->
    <xs:element name="register_group">
        <xs:complexType>
        <xs:sequence>
            <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <!-- Define attributes for register group element -->
        <xs:attribute name="name" type="c_symbol_type" use="required"></xs:attribute>
        <xs:attribute name="filter" type="xs:string" />
        <xs:attribute name="display_by_default" type="booleanEnum"/>
        </xs:complexType>
    </xs:element>

    <!-- Define peripheral Element -->
    <xs:element name="peripheral">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="register" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <!-- Define attributes for peripheral element -->
            <xs:attribute name="name" type="c_symbol_type" use="required"></xs:attribute>
            <xs:attribute name="offset" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- Define gui_name element -->
    <xs:element name="gui_name">
        <xs:complexType mixed="true">
          <xs:attribute name="language" type="xs:language" use="required"/> 
        </xs:complexType>
    </xs:element>
  
    <!-- Define Description Element -->
    <xs:element name="description">
        <xs:complexType mixed="true">
        <xs:attribute name="language" type="xs:language" use="required"/> 
        </xs:complexType>
    </xs:element>
    
    <!--  Define Disable Condition Element -->
    <xs:element name="disable_condition" type="xs:string"/>
  
    <!-- Define Register Element -->
    <xs:element name="register">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="alias_name" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="device_name" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
                <xs:choice>
                  <xs:choice minOccurs="0" maxOccurs="unbounded">
                      <xs:element ref="bitField" minOccurs="0" maxOccurs="unbounded"/>
                      <xs:element ref="conditional" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:element ref="array" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
                <xs:element name="device_register" type="device_register_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="size" type="widthEnum" use="required" />
            <xs:attribute name="offset" type="xs:string" />
            <xs:attribute name="access" type="accessEnum" use="required"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="optional" default="Hex"/>
            <xs:attribute name="display_by_default" type="booleanEnum"/>
            <xs:attribute name="doclink" type="xs:string" />
            <xs:attribute name="hidden" type="booleanEnum"/>
        </xs:complexType>
    </xs:element>

    <!-- Define conditional inclusion of bitfields -->
    <xs:element name="conditional">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bitField" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="expr" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <!-- Define alias_name Element -->
    <xs:element name="alias_name" type="xs:string"/>
    
    <!-- Define bitField Element -->
    <xs:element name="bitField">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="definition" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="conditional" type="booleanEnum" use="optional"/>
            <xs:attribute name="enumerationId" use="optional"/>
            <xs:attribute name="high_bit" type="bitFieldSize" use="optional"/>
            <xs:attribute name="low_bit" type="bitFieldSize" use="optional"/>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="access" type="accessEnum" use="optional" default="RW"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="optional" default="Hex"/>
        </xs:complexType>
    </xs:element>

    <!-- Define array types -->
    <xs:element name="array">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="element_bits"  type="xs:decimal" use="required"/>
            <xs:attribute name="element_stride"  type="xs:decimal" use="optional"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="required"/>
            <xs:attribute name="index_from_lsb" type="booleanEnum" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="definition" type="bitFieldPattern" />
  
    <!-- User defined types -->
    
    <!-- Definition boolean enumeration-->
    <xs:simpleType name="booleanEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="false"/>
            <xs:enumeration value="true"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Definition width enumeration-->
    <xs:simpleType name="widthEnum">
          <xs:restriction base="xs:string">
            <xs:enumeration value="256"/>
            <xs:enumeration value="128"/>
            <xs:enumeration value="64"/>
            <xs:enumeration value="32"/>
            <xs:enumeration value="16"/>
            <xs:enumeration value="8"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="1"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Definition of Access enumeration -->
    <xs:simpleType name="accessEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RW"/>
            <xs:enumeration value="RO"/>
            <xs:enumeration value="WO"/>
            <xs:enumeration value="RMW"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Define Pattern for Bit field definition element -->
    <xs:simpleType name="bitFieldPattern">
        <xs:restriction base="xs:string">
        <xs:pattern value="((\[[0-9]+\])|(\[[0-9]+:[0-9]+\]))+"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Define range for bit fields -->
    <xs:simpleType name="bitFieldSize">
        <xs:restriction base="xs:decimal">
            <xs:maxInclusive value="31"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- <device_register name="D0" high_bit="31" low_bit="0" shift="0"/> -->
    <xs:complexType name="device_register_type">
        <xs:attribute name="name" type="tcf:NameType"/>
        <xs:attribute name="high_bit" type="bitFieldSize_128"/>
        <xs:attribute name="low_bit" type="bitFieldSize_128"/>
        <xs:attribute name="shift" type="xs:decimal"/>
    </xs:complexType>
    
    <xs:simpleType name="bitFieldSize_128">
        <xs:restriction base="xs:decimal">
            <xs:maxInclusive value="127"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="c_symbol_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_$][a-zA-Z_$0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="device_name">
        <xs:complexType mixed="true">
          <xs:attribute name="type" type="xs:string"/> 
        </xs:complexType>
    </xs:element>

    <!-- Format of bit field inclusion file -->
    <xs:element name="bitFields">
        <xs:complexType>
            <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="bitField" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="array" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="xml:specialAttrs"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="register_list_type">
        <xs:sequence>
            <xs:element name="access_world" type="tcf:addrTypeEnum" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="xi:include"/>
                <xs:element ref="register_group"/>
                <xs:element ref="peripheral" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:element ref="tcf:enumeration" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="filter" type="xs:string" />
        <xs:attribute name="display_by_default" type="booleanEnum"/>
        <xs:attribute name="override" type="booleanEnum"/>      
        <xs:attributeGroup ref="xml:specialAttrs"/>
    </xs:complexType>

    <!-- Definition of Access enumeration -->
    <xs:simpleType name="numericalDisplayFormat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hex"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="Int"/>
            <xs:enumeration value="UnsignedInt"/>
            <xs:enumeration value="Binary"/>
            <xs:enumeration value="Boolean"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Jegeva/ads2svd/in/Cores/Registers/CP15/ARM1156T2F-S_TCM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<register_list
    name="CP15"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.arm.com/core_reg"
    xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd"
    xmlns:tcf="http://com.arm.targetconfigurationeditor">
    <register_group name="TCM">
        <gui_name language="en">TCM</gui_name>
        <description language="en">Tightly Coupled Memory control</description>
        <register access="RO" name="TCM_STATUS" size="4">
            <gui_name language="en">TCM Status</gui_name>
            <alias_name>CP15_TCM_STATUS</alias_name>
            <device_name type="rvi">CP15_TCM_STATUS</device_name>
            <device_name type="cadi">CP15_TCM_STATUS</device_name>
            <description language="en">Specifies the number of instruction and data TCMs in the system</description>
            <bitField conditional="false" name="DTCM">
                <gui_name language="en">DTCM</gui_name>
                <description language="en">Specifies the number of data TCM banks implemented</description>
                <definition>[18:16]</definition>
            </bitField>
            <bitField conditional="false" name="ITCM">
                <gui_name language="en">ITCM</gui_name>
                <description language="en">Specifies the number of instruction TCM banks implemented</description>
                <definition>[2:0]</definition>
            </bitField>
        </register>
        <register access="RW" name="DTCM_REGION" size="4">
            <gui_name language="en">Data TCM Region</gui_name>
            <alias_name>CP15_DTCM_REGION</alias_name>
            <device_name type="rvi">CP15_DTCM_REGION</device_name>
            <device_name type="cadi">CP15_DTCM_REGION</device_name>
            <description language="en">Holds the base address, size and enable bit of the data TCM</description>
            <bitField conditional="false" name="Base_address">
                <gui_name language="en">Base address</gui_name>
                <description language="en">Defines the physical base address of the data TCM</description>
                <definition>[31:12]</definition>
            </bitField>
            <bitField conditional="false" name="Size" enumerationId="CP15_XTCM_REGION_SIZE">
                <gui_name language="en">Size</gui_name>
                <description language="en">Defines the size of the data TCM on reads</description>
                <definition>[6:2]</definition>
            </bitField>
            <bitField conditional="false" name="Enable">
                <gui_name language="en">Enable</gui_name>
                <description language="en">Enables or disables the data TCM</description>
                <definition>[0]</definition>
            </bitField>
        </register>
        <register access="RW" name="ITCM_REGION" size="4">
            <gui_name language="en">Instruction TCM Region</gui_name>
            <alias_name>CP15_ITCM_REGION</alias_name>
            <device_name type="rvi">CP15_ITCM_REGION</device_name>
            <device_name type="cadi">CP15_ITCM_REGION</device_name>
            <description language="en">Holds the base address, size and enable bit of the instruction TCM</description>
            <bitField conditional="false" name="Base_address">
                <gui_name language="en">Base address</gui_name>
                <description language="en">Defines the physical base address of the instruction TCM</description>
                <definition>[31:12]</definition>
            </bitField>
            <bitField conditional="false" name="Size" enumerationId="CP15_XTCM_REGION_SIZE">
                <gui_name language="en">Size</gui_name>
                <description language="en">Defines the size of the instruction TCM on reads</description>
                <definition>[6:2]</definition>
            </bitField>
            <bitField conditional="false" name="Enable">
                <gui_name language="en">Enable</gui_name>
                <description language="en">Enables or disables the instruction TCM</description>
                <definition>[0]</definition>
            </bitField>
        </register>
    </register_group>
</register_list>

=== Jegeva/ads2svd/in/Cores/Registers/System/A73_AARCH32_ImpDef.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<register_list xmlns="http://www.arm.com/core_reg" xmlns:tcf="http://com.arm.targetconfigurationeditor" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="System" xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd">
    <register_group name="ImplementationDefined">
        <gui_name language="en">Implementation Defined</gui_name>
        <description language="en">Implementation Defined</description>
        <register access="RW" name="L2CTLR" size="4">
            <gui_name language="en">L2 Control Register</gui_name>
            <description language="en">L2 Control Register.</description>
        </register>
        <register access="RW" name="L2ECTLR" size="4">
            <gui_name language="en">L2 Extended Control Register</gui_name>
            <description language="en">L2 Extended Control Register.</description>
        </register>
        <register access="RO" name="CBAR" size="4">
            <gui_name language="en">Configuration Base Address Register</gui_name>
            <description language="en">Configuration Base Address Register.</description>
        </register>
        <register access="RW" name="ECTLR" size="4">
            <gui_name language="en">Extended Control Register</gui_name>
            <description language="en">Extended Control Register.</description>
        </register>
        <register access="RW" name="L2MERRSR" size="8">
            <gui_name language="en">L2 Memory Error Syndrome Register</gui_name>
            <description language="en">L2 Memory Error Syndrome Register.</description>
        </register>
    </register_group>
</register_list>

=== Jegeva/ads2svd/in/Cores/Registers/System/ARMv8.1/V8_AARCH64_Address.xml
<?xml version="1.0" encoding="UTF-8"?>
<register_list name="System" xmlns="http://www.arm.com/core_reg" xmlns:tcf="http://com.arm.targetconfigurationeditor" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd">
  <!--PLEASE DO NOT EDIT THIS FILE - Generated from SysReg_v81A_xml-00bet3-->
  <register_group name="Address">
    <gui_name language="en">Address</gui_name>
    <description language="en">Address</description>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-par_el1.html" name="PAR_EL1" size="8">
      <gui_name language="en">Physical Address Register</gui_name>
      <description language="en">Returns the output address (OA) from an Address translation instruction that executed successfully, or fault information if the instruction did not execute successfully.</description>
      <bitField enumerationId="PAR_EL1_F" name="F">
        <gui_name language="en">F</gui_name>
        <description language="en">Indicates whether the instruction performed a successful address translation.</description>
        <definition>[0]</definition>
      </bitField>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s12e0r.html" name="AT_S12E0R" size="8">
      <gui_name language="en">Address Translate Stages 1 and 2 EL0 Read</gui_name>
      <device_name type="rvi">AT_S12E0R</device_name>
      <device_name type="cadi">AT S12E0R</device_name>
      <description language="en">Performs stage 1 and 2 address translations, with permissions as if reading from the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s12e0w.html" name="AT_S12E0W" size="8">
      <gui_name language="en">Address Translate Stages 1 and 2 EL0 Write</gui_name>
      <device_name type="rvi">AT_S12E0W</device_name>
      <device_name type="cadi">AT S12E0W</device_name>
      <description language="en">Performs stage 1 and 2 address translations, with permissions as if writing to the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s12e1r.html" name="AT_S12E1R" size="8">
      <gui_name language="en">Address Translate Stages 1 and 2 EL1 Read</gui_name>
      <device_name type="rvi">AT_S12E1R</device_name>
      <device_name type="cadi">AT S12E1R</device_name>
      <description language="en">Performs stage 1 and 2 address translation, with permissions as if reading from the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s12e1w.html" name="AT_S12E1W" size="8">
      <gui_name language="en">Address Translate Stages 1 and 2 EL1 Write</gui_name>
      <device_name type="rvi">AT_S12E1W</device_name>
      <device_name type="cadi">AT S12E1W</device_name>
      <description language="en">Performs stage 1 and 2 address translation, with permissions as if writing to the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e0r.html" name="AT_S1E0R" size="8">
      <gui_name language="en">Address Translate Stage 1 EL0 Read</gui_name>
      <device_name type="rvi">AT_S1E0R</device_name>
      <device_name type="cadi">AT S1E0R</device_name>
      <description language="en">Performs stage 1 address translation, with permissions as if reading from the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e0w.html" name="AT_S1E0W" size="8">
      <gui_name language="en">Address Translate Stage 1 EL0 Write</gui_name>
      <device_name type="rvi">AT_S1E0W</device_name>
      <device_name type="cadi">AT S1E0W</device_name>
      <description language="en">Performs stage 1 address translation, with permissions as if writing to the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e1r.html" name="AT_S1E1R" size="8">
      <gui_name language="en">Address Translate Stage 1 EL1 Read</gui_name>
      <device_name type="rvi">AT_S1E1R</device_name>
      <device_name type="cadi">AT S1E1R</device_name>
      <description language="en">Performs stage 1 address translation, with permissions as if reading from the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e1w.html" name="AT_S1E1W" size="8">
      <gui_name language="en">Address Translate Stage 1 EL1 Write</gui_name>
      <device_name type="rvi">AT_S1E1W</device_name>
      <device_name type="cadi">AT S1E1W</device_name>
      <description language="en">Performs stage 1 address translation, with permissions as if writing to the given virtual address, using the following translation regime...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e2r.html" name="AT_S1E2R" size="8">
      <gui_name language="en">Address Translate Stage 1 EL2 Read</gui_name>
      <device_name type="rvi">AT_S1E2R</device_name>
      <device_name type="cadi">AT S1E2R</device_name>
      <description language="en">Performs stage 1 address translation as defined for EL2, with permissions as if reading from the given virtual address.</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e2w.html" name="AT_S1E2W" size="8">
      <gui_name language="en">Address Translate Stage 1 EL2 Write</gui_name>
      <device_name type="rvi">AT_S1E2W</device_name>
      <device_name type="cadi">AT S1E2W</device_name>
      <description language="en">Performs stage 1 address translation as defined for EL2, with permissions as if writing to the given virtual address.</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e3r.html" name="AT_S1E3R" size="8">
      <gui_name language="en">Address Translate Stage 1 EL3 Read</gui_name>
      <device_name type="rvi">AT_S1E3R</device_name>
      <device_name type="cadi">AT S1E3R</device_name>
      <description language="en">Performs stage 1 address translation as defined for EL3, with permissions as if reading from the given virtual address.</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch64-at-s1e3w.html" name="AT_S1E3W" size="8">
      <gui_name language="en">Address Translate Stage 1 EL3 Write</gui_name>
      <device_name type="rvi">AT_S1E3W</device_name>
      <device_name type="cadi">AT S1E3W</device_name>
      <description language="en">Performs stage 1 address translation as defined for EL3, with permissions as if writing to the given virtual address.</description>
    </register>
  </register_group>
  <tcf:enumeration name="PAR_EL1_F">
    <tcf:enumItem description="Address translation completed successfully." name="Address_translation_completed_successfully" number="0"/>
    <tcf:enumItem description="Address translation aborted." name="Address_translation_aborted" number="1"/>
  </tcf:enumeration>
</register_list>
