=== Jegeva/ads2svd/in/Schemas/core_register_definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.arm.com/core_reg" 
        xmlns="http://www.arm.com/core_reg" 
        elementFormDefault="qualified"
        xmlns:xi="http://www.w3.org/2001/XInclude"
        xmlns:tcf="http://com.arm.targetconfigurationeditor">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2009/01/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/XInclude.xsd"/>
    <xs:import namespace="http://com.arm.targetconfigurationeditor" schemaLocation="board-01.xsd"/>

    <!-- Definition of root element register List -->
    <xs:element name="register_list" type="register_list_type"/>
  
  
    <!--  Define "container" element (used in include files) -->
    <xs:element name="container">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="register_list" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>  
        </xs:complexType>
    </xs:element>
  
    <!-- Define Register Group Element -->
    <xs:element name="register_group">
        <xs:complexType>
        <xs:sequence>
            <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <!-- Define attributes for register group element -->
        <xs:attribute name="name" type="c_symbol_type" use="required"></xs:attribute>
        <xs:attribute name="filter" type="xs:string" />
        <xs:attribute name="display_by_default" type="booleanEnum"/>
        </xs:complexType>
    </xs:element>

    <!-- Define peripheral Element -->
    <xs:element name="peripheral">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="register" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <!-- Define attributes for peripheral element -->
            <xs:attribute name="name" type="c_symbol_type" use="required"></xs:attribute>
            <xs:attribute name="offset" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- Define gui_name element -->
    <xs:element name="gui_name">
        <xs:complexType mixed="true">
          <xs:attribute name="language" type="xs:language" use="required"/> 
        </xs:complexType>
    </xs:element>
  
    <!-- Define Description Element -->
    <xs:element name="description">
        <xs:complexType mixed="true">
        <xs:attribute name="language" type="xs:language" use="required"/> 
        </xs:complexType>
    </xs:element>
    
    <!--  Define Disable Condition Element -->
    <xs:element name="disable_condition" type="xs:string"/>
  
    <!-- Define Register Element -->
    <xs:element name="register">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="alias_name" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="device_name" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="disable_condition" minOccurs="0" maxOccurs="1"/>
                <xs:choice>
                  <xs:choice minOccurs="0" maxOccurs="unbounded">
                      <xs:element ref="bitField" minOccurs="0" maxOccurs="unbounded"/>
                      <xs:element ref="conditional" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:element ref="array" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
                <xs:element name="device_register" type="device_register_type" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="xi:include" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="size" type="widthEnum" use="required" />
            <xs:attribute name="offset" type="xs:string" />
            <xs:attribute name="access" type="accessEnum" use="required"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="optional" default="Hex"/>
            <xs:attribute name="display_by_default" type="booleanEnum"/>
            <xs:attribute name="doclink" type="xs:string" />
            <xs:attribute name="hidden" type="booleanEnum"/>
        </xs:complexType>
    </xs:element>

    <!-- Define conditional inclusion of bitfields -->
    <xs:element name="conditional">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bitField" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="expr" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <!-- Define alias_name Element -->
    <xs:element name="alias_name" type="xs:string"/>
    
    <!-- Define bitField Element -->
    <xs:element name="bitField">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="definition" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="conditional" type="booleanEnum" use="optional"/>
            <xs:attribute name="enumerationId" use="optional"/>
            <xs:attribute name="high_bit" type="bitFieldSize" use="optional"/>
            <xs:attribute name="low_bit" type="bitFieldSize" use="optional"/>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="access" type="accessEnum" use="optional" default="RW"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="optional" default="Hex"/>
        </xs:complexType>
    </xs:element>

    <!-- Define array types -->
    <xs:element name="array">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gui_name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="c_symbol_type" use="required"/>
            <xs:attribute name="element_bits"  type="xs:decimal" use="required"/>
            <xs:attribute name="element_stride"  type="xs:decimal" use="optional"/>
            <xs:attribute name="format" type="numericalDisplayFormat" use="required"/>
            <xs:attribute name="index_from_lsb" type="booleanEnum" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="definition" type="bitFieldPattern" />
  
    <!-- User defined types -->
    
    <!-- Definition boolean enumeration-->
    <xs:simpleType name="booleanEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="false"/>
            <xs:enumeration value="true"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Definition width enumeration-->
    <xs:simpleType name="widthEnum">
          <xs:restriction base="xs:string">
            <xs:enumeration value="256"/>
            <xs:enumeration value="128"/>
            <xs:enumeration value="64"/>
            <xs:enumeration value="32"/>
            <xs:enumeration value="16"/>
            <xs:enumeration value="8"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="1"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Definition of Access enumeration -->
    <xs:simpleType name="accessEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RW"/>
            <xs:enumeration value="RO"/>
            <xs:enumeration value="WO"/>
            <xs:enumeration value="RMW"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Define Pattern for Bit field definition element -->
    <xs:simpleType name="bitFieldPattern">
        <xs:restriction base="xs:string">
        <xs:pattern value="((\[[0-9]+\])|(\[[0-9]+:[0-9]+\]))+"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- Define range for bit fields -->
    <xs:simpleType name="bitFieldSize">
        <xs:restriction base="xs:decimal">
            <xs:maxInclusive value="31"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
  
    <!-- <device_register name="D0" high_bit="31" low_bit="0" shift="0"/> -->
    <xs:complexType name="device_register_type">
        <xs:attribute name="name" type="tcf:NameType"/>
        <xs:attribute name="high_bit" type="bitFieldSize_128"/>
        <xs:attribute name="low_bit" type="bitFieldSize_128"/>
        <xs:attribute name="shift" type="xs:decimal"/>
    </xs:complexType>
    
    <xs:simpleType name="bitFieldSize_128">
        <xs:restriction base="xs:decimal">
            <xs:maxInclusive value="127"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="c_symbol_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_$][a-zA-Z_$0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="device_name">
        <xs:complexType mixed="true">
          <xs:attribute name="type" type="xs:string"/> 
        </xs:complexType>
    </xs:element>

    <!-- Format of bit field inclusion file -->
    <xs:element name="bitFields">
        <xs:complexType>
            <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="bitField" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="array" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="xml:specialAttrs"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="register_list_type">
        <xs:sequence>
            <xs:element name="access_world" type="tcf:addrTypeEnum" minOccurs="0" maxOccurs="1"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="xi:include"/>
                <xs:element ref="register_group"/>
                <xs:element ref="peripheral" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:element ref="tcf:enumeration" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="filter" type="xs:string" />
        <xs:attribute name="display_by_default" type="booleanEnum"/>
        <xs:attribute name="override" type="booleanEnum"/>      
        <xs:attributeGroup ref="xml:specialAttrs"/>
    </xs:complexType>

    <!-- Definition of Access enumeration -->
    <xs:simpleType name="numericalDisplayFormat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hex"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="Int"/>
            <xs:enumeration value="UnsignedInt"/>
            <xs:enumeration value="Binary"/>
            <xs:enumeration value="Boolean"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Jegeva/ads2svd/in/Cores/Registers/CP15/Cortex-v7A_Faults.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<register_list name="CP15"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.arm.com/core_reg"
    xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:tcf="http://com.arm.targetconfigurationeditor">
    <register_group name="FaultHandling">
        <gui_name language="en">Fault Handling</gui_name>
        <description language="en">PL1 Fault-Handling Registers</description>
        <register access="RW" name="DFSR" size="4">
            <gui_name language="en">DFSR</gui_name>
            <alias_name>CP15_DFSR</alias_name>
            <device_name type="rvi">CP15_DFSR</device_name>
            <device_name type="cadi">DFSR</device_name>
            <device_name type="rvi">CP15_DFSR</device_name>
            <device_name type="cadi">DFSR</device_name>
            <description language="en">Data Fault Status</description>
            <bitField conditional="false" name="CM" enumerationId="DFSR_CM">
                <gui_name language="en">CM</gui_name>
                <description language="en">Cache Maintenance</description>
                <definition>[13]</definition>
            </bitField>
            <bitField conditional="false" name="EXT">
                <gui_name language="en">EXT</gui_name>
                <description language="en">External abort type</description>
                <definition>[12]</definition>
            </bitField>
            <bitField conditional="false" name="WNR" enumerationId="DFSR_WNR">
                <gui_name language="en">WnR</gui_name>
                <description language="en">Access type causing abort</description>
                <definition>[11]</definition>
            </bitField>
            <bitField conditional="false" name="FS">
                <gui_name language="en">FS</gui_name>
                <description language="en">Fault Status</description>
                <definition>[3:0][10]</definition>
            </bitField>
        </register>
        <register access="RW" name="IFSR" size="4">
            <gui_name language="en">IFSR</gui_name>
            <alias_name>CP15_IFSR</alias_name>
            <device_name type="rvi">CP15_IFSR</device_name>
            <device_name type="cadi">IFSR</device_name>
            <device_name type="rvi">CP15_IFSR</device_name>
            <device_name type="cadi">IFSR</device_name>
            <description language="en">Instruction Fault Status</description>
            <bitField conditional="false" name="EXT">
                <gui_name language="en">EXT</gui_name>
                <description language="en">External abort type</description>
                <definition>[12]</definition>
            </bitField>
            <bitField conditional="false" enumerationId="FAULTS_IFSR_FS" name="FS">
                <gui_name language="en">FS</gui_name>
                <description language="en">Fault Status</description>
                <definition>[3:0][10]</definition>
            </bitField>
        </register>
        <register access="RW" name="AIFSR" size="4">
            <gui_name language="en">AIFSR</gui_name>
            <alias_name>CP15_AIFSR</alias_name>
            <device_name type="rvi">CP15_AIFSR</device_name>
            <device_name type="cadi">AIFSR</device_name>
            <device_name type="rvi">CP15_AIFSR</device_name>
            <device_name type="cadi">AIFSR</device_name>
            <description language="en">Auxiliary Instruction Fault Status</description>
            <!-- Cortex-A7, A12 and A15 do not implement ADFSR, so this register is always UNK/SBZP. -->
        </register>
        <register access="RW" name="DFAR" size="4">
            <gui_name language="en">DFAR</gui_name>
            <alias_name>CP15_DFAR</alias_name>
            <device_name type="rvi">CP15_DFAR</device_name>
            <device_name type="cadi">DFAR</device_name>
            <device_name type="rvi">CP15_DFAR</device_name>
            <device_name type="cadi">DFAR</device_name>
            <description language="en">Data Fault Address</description>
        </register>
        <register access="RW" name="IFAR" size="4">
            <gui_name language="en">IFAR</gui_name>
            <alias_name>CP15_IFAR</alias_name>
            <device_name type="rvi">CP15_IFAR</device_name>
            <device_name type="cadi">IFAR</device_name>
            <device_name type="rvi">CP15_IFAR</device_name>
            <device_name type="cadi">IFAR</device_name>
            <description language="en">Instruction Fault Address</description>
        </register>
    </register_group>
</register_list>

=== Jegeva/ads2svd/in/Cores/Registers/System/ARMv8.1/V8_AARCH32_Thread.xml
<?xml version="1.0" encoding="UTF-8"?>
<register_list name="System" xmlns="http://www.arm.com/core_reg" xmlns:tcf="http://com.arm.targetconfigurationeditor" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd">
  <!--PLEASE DO NOT EDIT THIS FILE - Generated from SysReg_v81A_xml-00bet3-->
  <register_group name="Thread">
    <gui_name language="en">Thread</gui_name>
    <description language="en">Thread</description>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-htpidr.html" name="HTPIDR" size="4">
      <gui_name language="en">Hyp Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software running in Hyp mode can store thread identifying information that is not visible to Non-secure software executing at EL0 or EL1, for hypervisor management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidrprw.html" name="TPIDRPRW" size="4">
      <gui_name language="en">PL1 Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL1 or higher can store thread identifying information that is not visible to software executing at EL0, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidrprw.html" name="S_TPIDRPRW" size="4">
      <gui_name language="en">PL1 Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL1 or higher can store thread identifying information that is not visible to software executing at EL0, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidrprw.html" name="N_TPIDRPRW" size="4">
      <gui_name language="en">PL1 Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL1 or higher can store thread identifying information that is not visible to software executing at EL0, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidruro.html" name="TPIDRURO" size="4">
      <gui_name language="en">PL0 Read-Only Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL1 or higher can store thread identifying information that is visible to software executing at EL0, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidruro.html" name="S_TPIDRURO" size="4">
      <gui_name language="en">PL0 Read-Only Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL1 or higher can store thread identifying information that is visible to software executing at EL0, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidruro.html" name="N_TPIDRURO" size="4">
      <gui_name language="en">PL0 Read-Only Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL1 or higher can store thread identifying information that is visible to software executing at EL0, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidrurw.html" name="TPIDRURW" size="4">
      <gui_name language="en">PL0 Read/Write Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL0 can store thread identifying information, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidrurw.html" name="S_TPIDRURW" size="4">
      <gui_name language="en">PL0 Read/Write Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL0 can store thread identifying information, for OS management purposes...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_v81A_xml-00bet3/xhtml/AArch32-tpidrurw.html" name="N_TPIDRURW" size="4">
      <gui_name language="en">PL0 Read/Write Software Thread ID Register</gui_name>
      <description language="en">Provides a location where software executing at EL0 can store thread identifying information, for OS management purposes...</description>
    </register>
  </register_group>
</register_list>

=== Jegeva/ads2svd/in/Cores/Registers/System/V8-M_SIG.xml
<?xml version="1.0" encoding="UTF-8"?>
<register_list name="System" xmlns="http://www.arm.com/core_reg" xmlns:tcf="http://com.arm.targetconfigurationeditor" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd">
  <!--PLEASE DO NOT EDIT THIS FILE - Generated from JSON register descriptions-->
  <register_group name="SIG">
    <gui_name language="en">SIG</gui_name>
    <description language="en">Software Interrupt Control</description>
    <register access="WO" name="STIR" offset="0xE000EF00" size="4">
      <gui_name language="en">Software Triggered Interrupt Register</gui_name>
      <description language="en">Provides a mechanism for software to generate an interrupt</description>
      <bitField conditional="false" name="INTID">
        <gui_name language="en">INTID</gui_name>
        <description language="en">Interrupt ID</description>
        <definition>[8:0]</definition>
      </bitField>
    </register>
  </register_group>
</register_list>

=== Jegeva/ads2svd/in/Cores/Registers/System/ARMv8.0/V8_AARCH32_Legacy.xml
<?xml version="1.0" encoding="UTF-8"?>
<register_list name="System" xmlns="http://www.arm.com/core_reg" xmlns:tcf="http://com.arm.targetconfigurationeditor" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd">
  <!--PLEASE DO NOT EDIT THIS FILE - Generated from SysReg_xml-00bet19-->
  <register_group name="Legacy">
    <gui_name language="en">Legacy</gui_name>
    <description language="en">Legacy</description>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_xml-00bet19/xhtml/AArch32-cp15dmb.html" name="CP15DMB" size="4">
      <gui_name language="en">Data Memory Barrier System instruction</gui_name>
      <description language="en">Performs a Data Memory Barrier...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_xml-00bet19/xhtml/AArch32-cp15dsb.html" name="CP15DSB" size="4">
      <gui_name language="en">Data Synchronization Barrier System instruction</gui_name>
      <description language="en">Performs a Data Synchronization Barrier...</description>
    </register>
    <register access="WO" doclink="CDB://../../../Docs/SysReg_xml-00bet19/xhtml/AArch32-cp15isb.html" name="CP15ISB" size="4">
      <gui_name language="en">Instruction Synchronization Barrier System instruction</gui_name>
      <description language="en">Performs an Instruction Synchronization Barrier...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_xml-00bet19/xhtml/AArch32-fcseidr.html" name="FCSEIDR" size="4">
      <gui_name language="en">FCSE Process ID register</gui_name>
      <description language="en">Identifies whether the Fast Context Switch Extension (FCSE) is implemented...</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_xml-00bet19/xhtml/AArch32-jidr.html" name="JIDR" size="4">
      <gui_name language="en">Jazelle ID Register</gui_name>
      <description language="en">A Jazelle register, which identified the Jazelle architecture version.</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_xml-00bet19/xhtml/AArch32-jmcr.html" name="JMCR" size="4">
      <gui_name language="en">Jazelle Main Configuration Register</gui_name>
      <description language="en">A Jazelle register, which provides control of the Jazelle extension.</description>
    </register>
    <register access="RW" doclink="CDB://../../../Docs/SysReg_xml-00bet19/xhtml/AArch32-joscr.html" name="JOSCR" size="4">
      <gui_name language="en">Jazelle OS Control Register</gui_name>
      <description language="en">A Jazelle register, which provides operating system control of the Jazelle Extension.</description>
    </register>
  </register_group>
</register_list>

=== Jegeva/ads2svd/in/Cores/Registers/System/A53_AARCH64_ImpDef.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<register_list xmlns="http://www.arm.com/core_reg" xmlns:tcf="http://com.arm.targetconfigurationeditor" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="System" xsi:schemaLocation="http://www.arm.com/core_reg ../../../Schemas/core_register_definition.xsd">
    <register_group name="ImplementationDefined">
        <gui_name language="en">Implementation Defined</gui_name>
        <description language="en">Implementation Defined</description>
        <register access="RW" name="L2CTLR_EL1" size="4">
            <gui_name language="en">L2 Control Register</gui_name>
            <description language="en">L2 Control Register.</description>
        </register>
        <register access="RW" name="L2ECTLR_EL1" size="4">
            <gui_name language="en">L2 Extended Control Register</gui_name>
            <description language="en">L2 Extended Control Register.</description>
        </register>
        <register access="WO" name="RAMINDEX" size="4">
            <gui_name language="en">RAM Index Operation</gui_name>
            <device_name type="rvi">RAMINDEX_AA64</device_name>
            <description language="en">RAM Index Operation.</description>
        </register>
        <register access="RW" name="L2ACTLR_EL1" size="4">
            <gui_name language="en">L2 Auxiliary Control Register</gui_name>
            <description language="en">L2 Auxiliary Control Register.</description>
        </register>
        <register access="RO" name="CBAR_EL1" size="4">
            <gui_name language="en">Configuration Base Address Register</gui_name>
            <description language="en">Configuration Base Address Register.</description>
        </register>
        <register access="RW" name="CPUACTLR_EL1" size="8">
            <gui_name language="en">CPU Auxiliary Control Register</gui_name>
            <description language="en">CPU Auxiliary Control Register.</description>
        </register>
        <register access="RW" name="CPUECTLR_EL1" size="8">
            <gui_name language="en">CPU Extended Control Register</gui_name>
            <description language="en">CPU Extended Control Register.</description>
        </register>
        <register access="RW" name="CPUMERRSR_EL1" size="8">
            <gui_name language="en">CPU Memory Error Syndrome Register</gui_name>
            <description language="en">CPU Memory Error Syndrome Register.</description>
        </register>
        <register access="RW" name="L2MERRSR_EL1" size="8">
            <gui_name language="en">L2 Memory Error Syndrome Register</gui_name>
            <description language="en">L2 Memory Error Syndrome Register.</description>
        </register>
    </register_group>
</register_list>
