=== Jegeva/ads2svd/in/Schemas/flash_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.arm.com/flash_config"
            xmlns="http://www.arm.com/flash_config"
            xmlns:xi="http://www.w3.org/2001/XInclude"
            elementFormDefault="qualified">
     
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2009/01/xml.xsd"/>

 
     <xs:element name="flash_config">
        <xs:complexType>
            <xs:complexContent>
                <xs:restriction base="xs:anyType">
                    <xs:sequence>
                        <xs:element name="devices" type="flash_device_list" maxOccurs="1"/>
                        <xs:element name="method_configs" type="flash_method_config_list" maxOccurs="1"/>
                    </xs:sequence>
                </xs:restriction>
            </xs:complexContent>
        </xs:complexType>      
    </xs:element>
 
     <xs:complexType name="flash_device_list">
        <xs:complexContent> 
            <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="device" type="flash_device_type" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="flash_region_type">
        <xs:attribute name="address" type="xs:string" use="required"/>
        <xs:attribute name="size"    type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="flash_region_list">
         <xs:complexContent> 
             <xs:restriction base="xs:anyType">
               <xs:sequence>
                    <xs:element name="region" type="flash_region_type" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:restriction>
         </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="flash_device_type">    
         <xs:complexContent>
             <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="regions" type="flash_region_list" minOccurs="0"/>
                    <xs:element name="programming_type" type="flash_programming_type"/>
                </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="description" type="xs:string" use="optional"/>
            </xs:restriction>
         </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="flash_programming_type">   
        <xs:complexContent> 
            <xs:restriction base="xs:anyType">  
                <xs:sequence>
                    <xs:element name="method" type="flash_method" minOccurs="1"/>
                    <xs:element name="setup" type="flash_script" minOccurs="0"/>
                    <xs:element name="teardown" type="flash_script" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:restriction>
        </xs:complexContent> 
    </xs:complexType>

    <xs:complexType name="flash_method">
        <xs:attribute name="language" type="xs:string" use="required"/>
        <xs:attribute name="script"   type="xs:string" use="required"/>
        <xs:attribute name="class"    type="xs:string" use="required"/>
        <xs:attribute name="method_config" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="flash_script">
        <xs:attribute name="script" type="xs:string" use="required"/>
        <xs:attribute name="method" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="flash_method_config_list">
        <xs:complexContent> 
            <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="method_config" type="flash_method_config" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent> 
    </xs:complexType>

    <xs:complexType name="flash_method_config">     
        <xs:complexContent>
            <xs:restriction base="xs:anyType"> 
                <xs:sequence>
                    <xs:element name="params" type="flash_params_list" maxOccurs="1"/>
                    <xs:element name="algorithm_characteristics" type="flash_algorithm_characteristics_list" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:restriction>
        </xs:complexContent> 
    </xs:complexType>

    <xs:complexType name="flash_parameter">
        <xs:attribute name="name"  type="xs:string" use="required"/>
        <xs:attribute name="type"  type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="flash_algorithm_characteristics_list">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="value" type="flash_parameter" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent> 
    </xs:complexType>

    <xs:complexType name="flash_params_list">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="param" type="flash_parameter" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent> 
    </xs:complexType>
</xs:schema>

=== Jegeva/ads2svd/in/Boards/Keil/MCB1760/keil-lpc1768_flash.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Copyright (C) 2012 ARM Limited. All rights reserved.-->
<flash_config
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.arm.com/flash_config"
    xsi:schemaLocation="http://www.arm.com/flash_config flash_config.xsd">
    <devices>
        <!-- The main flash device -->
        <device name="MainFlash">
            <programming_type type="FILE">
                <!-- Use the standard method for running Keil algorithms -->
                <method language="JYTHON" script="FDB://keil_flash.py" class="KeilFlash" method_config="Main"/>
                <!-- Target specific script to get target in a suitable state for programming -->
            </programming_type>
        </device>
    </devices>
    <method_configs>
        <!-- Parameters for programming the main flash -->
        <method_config id="Main">
            <params>
                <!-- Programming algorithm binary to load to target -->
                <param name="algorithm" type="string" value="FDB://algorithms/LPC_IAP_512.FLM"/>
                <!-- The core in the target to run the algorithm -->
                <param name="coreName" type="string" value="Cortex-M3"/>
                <!-- RAM location & size for algorithm code and write buffers -->
                <param name="ramAddress" type="integer" value="0x10000000"/>
                <param name="ramSize" type="integer" value="0x1000"/>
                <!-- Allow timeouts to be disabled -->
                <param name="disableTimeouts" type="string" value="false"/>
                        <param name="checkLPC17xx_Signature" type="string" value="true"/>
                <!-- Set to false to skip the verification stage -->
                <param name="verify" type="string" value="true"/>
            </params>
        </method_config>
    </method_configs>
</flash_config>

=== Jegeva/ads2svd/in/Boards/Spansion/S6J3110EJAA/S6J3110_flash.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Copyright (C) 2012-2013 ARM Limited. All rights reserved.-->
<flash_config
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.arm.com/flash_config"
    xsi:schemaLocation="http://www.arm.com/flash_config ../../../Schemas/flash_config.xsd">
    <devices>
        <!-- The main flash device -->
        <device name="TCFLASH">
            <programming_type type="FILE">
                <!-- Use the standard method for running Keil algorithms -->
                <method language="JYTHON" script="FDB://keil_flash.py" class="KeilFlash" method_config="TCFLASH"/>
                <!-- Target specific script to get target in a suitable state for programming -->
                <setup script="FDB://S6J3110_setup.py" method="setup"/>
            </programming_type>
        </device>
        <!-- The main flash device -->
        <device name="WORKFLASH">
            <programming_type type="FILE">
                <!-- Use the standard method for running Keil algorithms -->
                <method language="JYTHON" script="FDB://keil_flash.py" class="KeilFlash" method_config="WORKFLASH"/>
                <!-- Target specific script to get target in a suitable state for programming -->
                <setup script="FDB://S6J3110_setup.py" method="setup"/>
            </programming_type>
        </device>
    </devices>
    <method_configs>
        <!-- Parameters for programming the TCFLASH -->
        <method_config id="TCFLASH">
            <params>
                <!-- Programming algorithm binary to load to target -->
                <param name="algorithm" type="string" value="FDB://algorithms/S6J3110_TCFLASH.FLM"/>
                <!-- The core in the target to run the algorithm -->
                <param name="coreName" type="string" value="Cortex-R5"/>
                <!-- RAM location & size for algorithm code and write buffers -->
                <param name="ramAddress" type="integer" value="0x00000000"/>
                <param name="ramSize" type="integer" value="0x10000"/>
                <!-- Allow timeouts to be disabled -->
                <param name="disableTimeouts" type="string" value="false"/>
                <!-- Set to false to skip the verification stage -->
                <param name="verify" type="string" value="true"/>
            </params>
        </method_config>
        <!-- Parameters for programming the TCFLASH -->
        <method_config id="WORKFLASH">
            <params>
                <!-- Programming algorithm binary to load to target -->
                <param name="algorithm" type="string" value="FDB://algorithms/S6J3110_WORKFLASH.FLM"/>
                <!-- The core in the target to run the algorithm -->
                <param name="coreName" type="string" value="Cortex-R5"/>
                <!-- RAM location & size for algorithm code and write buffers -->
                <param name="ramAddress" type="integer" value="0x00000000"/>
                <param name="ramSize" type="integer" value="0x10000"/>
                <!-- Allow timeouts to be disabled -->
                <param name="disableTimeouts" type="string" value="false"/>
                <!-- Set to false to skip the verification stage -->
                <param name="verify" type="string" value="true"/>
            </params>
        </method_config>
    </method_configs>
</flash_config>
